// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logo-variants/Badge.tsx": () => import("../components/mockups/logo-variants/Badge.tsx"),
  "./components/mockups/logo-variants/Emblem.tsx": () => import("../components/mockups/logo-variants/Emblem.tsx"),
  "./components/mockups/logo-variants/Wordmark.tsx": () => import("../components/mockups/logo-variants/Wordmark.tsx")
};
